sudo: false
language: node_js
node_js:
  - node
os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      Xvfb :99 &
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run compile
  - npm test
  - npm run tslint